theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "networkmanager"
on_click = "alacritty  --class nmtui --title 'Network configuration' -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
device_format = "{icon}{ap}"

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"

[[block]]
block = "backlight"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

