theme = "slick"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "networkmanager"
primary_only = true
on_click = "kitty  --class nmtui --title 'Network configuration' nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
device_format = "{icon}{ap}"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"
marquee = false
max_width = 30
smart_trim = true
player = "clementine"
on_collapsed_click = "clementine"

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"

[[block]]
block = "backlight"
step_width = 1

[[block]]
block = "sound"
on_click = "pavucontrol"
step_width = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

